# Generated by Django 4.2.25 on 2026-01-07 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.ManyToManyField(related_name='Post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
