# Generated by Django 4.2.25 on 2025-11-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event_post_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
