# Generated by Django 4.2.25 on 2025-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_event_post_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
